workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    working_directory: flutter_emaam
    integrations:
      app_store_connect: Codemagic # This assumes you named your integration "Codemagic" or have only one.
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - apple_auth
      vars:
        APP_ID: 6742512345
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    scripts:
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "com.digitalbow.emaam" --type IOS_APP_STORE --create
          keychain add-certificates
      - name: Install dependencies
        script: |
          flutter packages pub get
          cd ios && pod install
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --build-name=1.0.3 \
            --build-number=4 \
            --export-options-plist=$HOME/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true

  android-release:
    name: Android Release Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    working_directory: flutter_emaam
    environment:
      flutter: stable
      groups:
        - google_play
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: |
          flutter packages pub get
      - name: Flutter build aab
        script: |
          flutter build appbundle --release \
            --build-name=1.0.3 \
            --build-number=4
    artifacts:
      - build/app/outputs/bundle/release/*.aab
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
