# The following line is added by the Flutter tool.
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), File.join(File.dirname(__FILE__), '..', '..'))

prepare_command 'ruby -e "require \'fileutils\'; FileUtils.touch(\'Flutter/Generated.xcconfig\')"'

platform :ios, '15.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
