# Uncomment this line to define a global platform for your project
platform :ios, '15.0'

# CocoaPods analytics sends network stats synchronously affecting build performance.
ENV['COCOAPODS_DISABLE_STATS'] = '1'

project 'Runner', {
  'Debug' => :debug,
  'Release' => :release,
  'Profile' => :profile,
}

def flutter_install_all_ios_pods(main_target_directory)
  return unless File.exist?(File.join(main_target_directory, 'Generated.xcconfig'))
  helper_dir = File.expand_path(File.join('..', '..', '..', 'packages', 'flutter_tools', 'bin'), __FILE__)
  system('ruby', File.join(helper_dir, 'patch_xcconfig.rb'), '--xcconfig-path', File.join(main_target_directory, 'Generated.xcconfig'))
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
