// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBozFwTNyNCGH8KBi0-D4OrxbRwrtIRfUw',
    appId: '1:490328842174:web:096fb2685384333e8a63ef',
    messagingSenderId: '490328842174',
    projectId: 'emaam-digitalbow',
    authDomain: 'emaam-digitalbow.firebaseapp.com',
    storageBucket: 'emaam-digitalbow.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeWvfKA1vB2MaI6MrZgZBMED3S29FWvWE',
    appId: '1:490328842174:android:006dc4fd6a833a608a63ef',
    messagingSenderId: '490328842174',
    projectId: 'emaam-digitalbow',
    storageBucket: 'emaam-digitalbow.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9DkkIch2Qw9hOrYBo1nAFpbSV1JG9_00',
    appId: '1:490328842174:ios:2cedd6e642c6f8f38a63ef',
    messagingSenderId: '490328842174',
    projectId: 'emaam-digitalbow',
    storageBucket: 'emaam-digitalbow.firebasestorage.app',
    iosBundleId: 'com.digitalbow.emaam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9DkkIch2Qw9hOrYBo1nAFpbSV1JG9_00',
    appId: '1:490328842174:ios:2cedd6e642c6f8f38a63ef',
    messagingSenderId: '490328842174',
    projectId: 'emaam-digitalbow',
    storageBucket: 'emaam-digitalbow.firebasestorage.app',
    iosBundleId: 'com.digitalbow.emaam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBozFwTNyNCGH8KBi0-D4OrxbRwrtIRfUw',
    appId: '1:490328842174:web:8ce8fb63cf84dd6c8a63ef',
    messagingSenderId: '490328842174',
    projectId: 'emaam-digitalbow',
    authDomain: 'emaam-digitalbow.firebaseapp.com',
    storageBucket: 'emaam-digitalbow.firebasestorage.app',
  );

}